// PHSXC Summer Team Board v30
const GOOGLE_APPS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbxrZU9YRCoi1giUkmyski0VrBzKpI1Tfrk--TYInwjK48yo7SCaT0I66mHbuW1Tc0Fp/exec";
const statusEl = document.getElementById("leaderboardStatus");
const resultsEl = document.getElementById("leaderboardResults");
const listEl = document.getElementById("leaderboardList");
const coachCodeInput = document.getElementById("coachCodeInput");
const unlockCoachViewBtn = document.getElementById("unlockCoachViewBtn");
const lockCoachViewBtn = document.getElementById("lockCoachViewBtn");
const coachViewStatus = document.getElementById("coachViewStatus");
let currentSort = "minutes";
let boardData = [];
let coachUnlocked = sessionStorage.getItem("phsxcCoachUnlocked") === "true";
function formatNumber(value, digits = 1) { const num = Number(value || 0); if (!Number.isFinite(num)) return "0"; if (Math.abs(num - Math.round(num)) < 0.001) return String(Math.round(num)); return num.toFixed(digits); }
function escapeHTML(str) { return String(str || "").replace(/[&<>"']/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char])); }
function requestViaJSONP(paramsObj) { return new Promise((resolve, reject) => { const callback = `phsxcCallback_${Date.now()}`; const params = new URLSearchParams({...paramsObj, callback, v: Date.now().toString()}); const scriptUrl = `${GOOGLE_APPS_SCRIPT_URL}${GOOGLE_APPS_SCRIPT_URL.includes("?") ? "&" : "?"}${params.toString()}`; const script = document.createElement("script"); const timeout = setTimeout(() => { cleanup(); reject(new Error("Request timed out. Please try again.")); }, 15000); function cleanup(){ clearTimeout(timeout); delete window[callback]; if (script.parentNode) script.parentNode.removeChild(script); } window[callback] = function(response){ cleanup(); if (response && response.ok) resolve(response); else reject(new Error(response?.error || "Request failed.")); }; script.onerror = function(){ cleanup(); reject(new Error("Could not connect. Check connection and try again.")); }; script.src = scriptUrl; document.body.appendChild(script); }); }
function loadViaJSONP(){ return requestViaJSONP({action:"getLeaderboard"}); }
function sortBoard(data){ const keyMap={minutes:"minutes",miles:"miles",gymDays:"gymDays",loggedDays:"loggedDays"}; const key=keyMap[currentSort]||"minutes"; return [...data].sort((a,b)=>{ const primary=Number(b[key]||0)-Number(a[key]||0); if(primary!==0) return primary; return String(a.displayName||"").localeCompare(String(b.displayName||"")); }); }
function renderCoachState(){ if(!coachCodeInput||!unlockCoachViewBtn||!lockCoachViewBtn||!coachViewStatus) return; coachCodeInput.hidden=coachUnlocked; unlockCoachViewBtn.hidden=coachUnlocked; lockCoachViewBtn.hidden=!coachUnlocked; if(coachUnlocked){ coachViewStatus.textContent="Coach View enabled. Tap a runner card to view that runner’s workout log."; coachViewStatus.className="form-status"; } else { coachViewStatus.textContent=""; coachViewStatus.className="form-status"; } }
function calculateTeamTotals(runners){ return runners.reduce((totals, runner)=>{ totals.minutes += Number(runner.minutes||0); totals.miles += Number(runner.miles||0); totals.entries += Number(runner.entries||0); totals.gymDays += Number(runner.gymDays||0); return totals; }, {minutes:0,miles:0,entries:0,gymDays:0}); }
function renderBoard(response){ boardData=response.runners||[]; const sorted=sortBoard(boardData); const team=response.teamTotals||calculateTeamTotals(boardData); renderCoachState(); resultsEl.hidden=false; document.getElementById("leaderboardSubtitle").textContent=`Showing ${sorted.length} runner${sorted.length===1?"":"s"} with submitted workout logs.`; document.getElementById("teamRunnersSummary").innerHTML=`${sorted.length}`; document.getElementById("teamMinutesSummary").innerHTML=`${formatNumber(team.minutes,0)} min`; document.getElementById("teamMilesSummary").innerHTML=`${formatNumber(team.miles,2)} mi`; if(!sorted.length){ listEl.innerHTML=`<p class="details">No workout logs have been submitted yet.</p>`; return; } listEl.innerHTML=sorted.map((runner,index)=>`<article class="leaderboard-row-card ${coachUnlocked?"coach-clickable":""}" data-athlete-id="${escapeHTML(runner.athleteId||"")}" data-display-name="${escapeHTML(runner.displayName||"Runner")}"><div class="rank-badge">${index+1}</div><div class="leaderboard-runner"><h3>${escapeHTML(runner.displayName||"Runner")}</h3><p>${runner.entries||0} entries · ${runner.loggedDays||0} logged days${coachUnlocked?" · Tap to view log":""}</p></div><div class="leaderboard-stats"><div><strong>${formatNumber(runner.minutes,0)}</strong><span>min</span></div><div><strong>${formatNumber(runner.miles,2)}</strong><span>mi</span></div><div><strong>${runner.gymDays||0}</strong><span>gym days</span></div></div></article>`).join(""); if(coachUnlocked){ document.querySelectorAll(".leaderboard-row-card").forEach(card=>{ card.addEventListener("click",()=>openCoachRunnerLog(card.dataset.athleteId, card.dataset.displayName)); }); } }
function openCoachRunnerLog(athleteId, displayName){ const coachCode=sessionStorage.getItem("phsxcCoachCode")||""; if(!coachCode||!athleteId){ coachUnlocked=false; sessionStorage.removeItem("phsxcCoachUnlocked"); renderBoard({ok:true,runners:boardData,teamTotals:calculateTeamTotals(boardData)}); return; } sessionStorage.setItem("phsxcCoachAthleteId", athleteId); sessionStorage.setItem("phsxcCoachDisplayName", displayName||""); window.location.href="coach-log.html"; }
async function loadBoard(){ statusEl.textContent="Loading team board…"; statusEl.className="form-status"; resultsEl.hidden=true; try{ const response=await loadViaJSONP(); renderBoard(response); statusEl.textContent=""; } catch(err){ statusEl.textContent=err.message||"Could not load the team board."; statusEl.className="form-status error"; } }
function wireSortButtons(){ document.querySelectorAll(".sort-choice").forEach(btn=>{ btn.addEventListener("click",()=>{ currentSort=btn.dataset.sort; document.querySelectorAll(".sort-choice").forEach(b=>b.classList.toggle("selected", b===btn)); if(boardData.length) renderBoard({ok:true,runners:boardData,teamTotals:calculateTeamTotals(boardData)}); }); }); }
async function unlockCoachView(){ const coachCode=String(coachCodeInput?.value||"").trim(); if(!coachCode){ coachViewStatus.textContent="Enter the coach code."; coachViewStatus.className="form-status error"; return; } coachViewStatus.textContent="Checking coach code…"; coachViewStatus.className="form-status"; try{ await requestViaJSONP({action:"validateCoachCode", coachCode}); sessionStorage.setItem("phsxcCoachUnlocked","true"); sessionStorage.setItem("phsxcCoachCode",coachCode); coachUnlocked=true; coachCodeInput.value=""; renderBoard({ok:true,runners:boardData,teamTotals:calculateTeamTotals(boardData)}); } catch(err){ sessionStorage.removeItem("phsxcCoachUnlocked"); sessionStorage.removeItem("phsxcCoachCode"); coachUnlocked=false; coachViewStatus.textContent="Coach code was not accepted."; coachViewStatus.className="form-status error"; renderCoachState(); } }
function lockCoachView(){ sessionStorage.removeItem("phsxcCoachUnlocked"); sessionStorage.removeItem("phsxcCoachCode"); sessionStorage.removeItem("phsxcCoachAthleteId"); sessionStorage.removeItem("phsxcCoachDisplayName"); coachUnlocked=false; renderBoard({ok:true,runners:boardData,teamTotals:calculateTeamTotals(boardData)}); }
document.getElementById("refreshBoardBtn").addEventListener("click",loadBoard); unlockCoachViewBtn?.addEventListener("click",unlockCoachView); lockCoachViewBtn?.addEventListener("click",lockCoachView); wireSortButtons(); renderCoachState(); loadBoard();
